%bcond_without tests
%bcond_without weak_deps

%global __os_install_post %(echo '%{__os_install_post}' | sed -e 's!/usr/lib[^[:space:]]*/brp-python-bytecompile[[:space:]].*$!!g')
%global __provides_exclude_from ^/opt/ros/galactic/.*$
%global __requires_exclude_from ^/opt/ros/galactic/.*$

Name:           ros-galactic-microstrain-inertial-driver
Version:        2.7.0
Release:        1%{?dist}%{?release_suffix}
Summary:        ROS microstrain_inertial_driver package

License:        MIT
URL:            https://github.com/LORD-MicroStrain/microstrain_inertial
Source0:        %{name}-%{version}.tar.gz

Requires:       ros-galactic-diagnostic-aggregator
Requires:       ros-galactic-diagnostic-updater
Requires:       ros-galactic-geometry-msgs
Requires:       ros-galactic-lifecycle-msgs
Requires:       ros-galactic-mavros-msgs
Requires:       ros-galactic-microstrain-inertial-msgs
Requires:       ros-galactic-nav-msgs
Requires:       ros-galactic-nmea-msgs
Requires:       ros-galactic-rclcpp-lifecycle
Requires:       ros-galactic-rosidl-default-runtime
Requires:       ros-galactic-sensor-msgs
Requires:       ros-galactic-std-msgs
Requires:       ros-galactic-std-srvs
Requires:       ros-galactic-tf2
Requires:       ros-galactic-tf2-geometry-msgs
Requires:       ros-galactic-tf2-ros
Requires:       ros-galactic-ros-workspace
BuildRequires:  curl
BuildRequires:  jq
BuildRequires:  libcurl-devel
BuildRequires:  ros-galactic-ament-cmake-gtest
BuildRequires:  ros-galactic-ament-cpplint
BuildRequires:  ros-galactic-diagnostic-updater
BuildRequires:  ros-galactic-geometry-msgs
BuildRequires:  ros-galactic-lifecycle-msgs
BuildRequires:  ros-galactic-mavros-msgs
BuildRequires:  ros-galactic-microstrain-inertial-msgs
BuildRequires:  ros-galactic-nav-msgs
BuildRequires:  ros-galactic-nmea-msgs
BuildRequires:  ros-galactic-rclcpp-lifecycle
BuildRequires:  ros-galactic-ros-environment
BuildRequires:  ros-galactic-rosidl-default-generators
BuildRequires:  ros-galactic-sensor-msgs
BuildRequires:  ros-galactic-std-msgs
BuildRequires:  ros-galactic-std-srvs
BuildRequires:  ros-galactic-tf2
BuildRequires:  ros-galactic-tf2-geometry-msgs
BuildRequires:  ros-galactic-tf2-ros
BuildRequires:  ros-galactic-ros-workspace
BuildRequires:  ros-galactic-rosidl-typesupport-fastrtps-c
BuildRequires:  ros-galactic-rosidl-typesupport-fastrtps-cpp
Provides:       %{name}-devel = %{version}-%{release}
Provides:       %{name}-doc = %{version}-%{release}
Provides:       %{name}-runtime = %{version}-%{release}
Provides:       ros-galactic-rosidl-interface-packages(member)

%if 0%{?with_weak_deps}
Supplements:    ros-galactic-rosidl-interface-packages(all)
%endif

%description
The ros_mscl package provides a driver for the LORD/Microstrain inertial
products.

%prep
%autosetup -p1

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/galactic/setup.sh" ]; then . "/opt/ros/galactic/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake3 \
    -UINCLUDE_INSTALL_DIR \
    -ULIB_INSTALL_DIR \
    -USYSCONF_INSTALL_DIR \
    -USHARE_INSTALL_PREFIX \
    -ULIB_SUFFIX \
    -DCMAKE_INSTALL_PREFIX="/opt/ros/galactic" \
    -DAMENT_PREFIX_PATH="/opt/ros/galactic" \
    -DCMAKE_PREFIX_PATH="/opt/ros/galactic" \
    -DSETUPTOOLS_DEB_LAYOUT=OFF \
    ..

%make_build

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/galactic/setup.sh" ]; then . "/opt/ros/galactic/setup.sh"; fi
%make_install -C obj-%{_target_platform}

%if 0%{?with_tests}
%check
# Look for a Makefile target with a name indicating that it runs tests
TEST_TARGET=$(%__make -qp -C obj-%{_target_platform} | sed "s/^\(test\|check\):.*/\\1/;t f;d;:f;q0")
if [ -n "$TEST_TARGET" ]; then
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/galactic/setup.sh" ]; then . "/opt/ros/galactic/setup.sh"; fi
CTEST_OUTPUT_ON_FAILURE=1 \
    %make_build -C obj-%{_target_platform} $TEST_TARGET || echo "RPM TESTS FAILED"
else echo "RPM TESTS SKIPPED"; fi
%endif

%files
/opt/ros/galactic

%changelog
* Fri Sep 23 2022 Rob Fisher <rob.fisher@parker.com> - 2.7.0-1
- Autogenerated by Bloom

* Wed May 25 2022 Rob Fisher <rob.fisher@parker.com> - 2.6.0-1
- Autogenerated by Bloom

* Tue Feb 15 2022 Rob Fisher <rob.fisher@parker.com> - 2.5.1-1
- Autogenerated by Bloom

* Thu Jan 27 2022 Rob Fisher <rob.fisher@parker.com> - 2.5.0-1
- Autogenerated by Bloom

* Wed Jan 05 2022 Rob Fisher <rob.fisher@parker.com> - 2.4.0-1
- Autogenerated by Bloom

* Wed Dec 22 2021 Rob Fisher <rob.fisher@parker.com> - 2.3.0-1
- Autogenerated by Bloom

